import type { Metadata } from "next";
import "./globals.css";
import clsx from "clsx";
import { PropsWithChildren } from "react";
import { roboto } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={clsx("antialiased ", `${roboto.className}`)}>
        <main className="bg-background w-full">{children}</main>
      </body>
    </html>
  );
}
